### ISSUE TITLE
Nginx support

### ISSUE THREAD

**Issue by krzysztofantczak** [NagiosEnterprises/nagiosvshell#13]
Hello,

Are You planning to support nginx instead of apache?

**Comment by chrislaskey** [comment]
Hey there!

As long as Nagios defaults to using Apache, this project will continue to support Apache.

If the question is to add an additional installer option for Nginx, I wouldn't rule that out down the road but there are no plans for that currently.

For clarity - it's entirely possible to run nagiosvshell with Nginx. It is a simple PHP application with an AngularJS front end. Creating a custom configuration should be straight forward.

I'll leave this issue open for others to comment on. I encourage anyone out there currently using Nagios or Nagios VShell with Nginx to post their configurations for others to adapt and learn from.

If this turns into a constructive conversation, we'd be happy to move the community documentation into the main repository for reference.

Thanks!

**Comment by krzysztofantczak** [comment]
Hey,

Thanks for quick response. I'm pretty familiar with those things behind vshell. I'm developing with Angular since almost 2 years now (and i was php developer over 8 years - now i've moved to node ;)), but that's why this project looks interesting. Anyway... i'm hitting in two obstacles here. First is nginx, i'm using it instead of apache in my setup with nagios. The second one is my OS, i'm freebsd guy and there's A LOT of issues here. I was trying to play around with vshell but it seems there is to many changes required to make it work on my box and i just don't have enough time to improve this project by my own. It would be awesome if someone with nginx+vshell or vshell+apache+freebsd expertise could help here ;-)

**Comment by krzysztofantczak** [comment]
Ok, i have managed to make it work, we can close this issue ;-)

**Comment by chrislaskey** [comment]
Glad to hear you've made it work! Thanks for sharing the gist of the changes required to get Nagios VShell to run under FreeBSD using Nginx.

I'm going to reopen the issue so it's a community resource for others to reference when looking for Nginx support.

**Comment by hedenface** [comment]
I'm going to *close* the issue, since there is no reason to leave a resolved issue open. Google still indexes the closed ones :)
