### ISSUE TITLE
Notes field in Servicegroup data

### ISSUE THREAD

**Issue by dsputnikk** [NagiosEnterprises/nagiosvshell#14]
I've been trying to hack apart the PHP in Vshell to try and populate an extra field in servicegroups grid to display the "Notes" field in nagios for a host. I'd also like to display this field in host details.

Could someone please help me out with this? Nagios is crucial to our infrastructure and I'd like a prettier front end - but we heavily leverage this notes field.

**Comment by mguthrie88** [comment]
Which Notes field are you needing to see in the UI, host notes, or service notes, or all?

**Comment by hedenface** [comment]
@dsputnikk If you come up with an answer, let us know and we'll be happy to update it!
