### ISSUE TITLE
Internal Server Error

### ISSUE THREAD

**Issue by longvo647912** [NagiosEnterprises/nagiosvshell#28]
I have problem when I try to connect Nagios core with V-shell 2

Host infomation:
Centos 7 on  VMware Workstation 17

** PROBLEM INFORMATION **
Internal Server Error

The server encountered an internal error or misconfiguration and was unable to complete your request.

Please contact the server administrator at root@localhost to inform them of the time this error occurred, and the actions you performed just before this error.

More information about this error may be available in the server error log.

![image](https://github.com/NagiosEnterprises/nagiosvshell/assets/142724383/148730c8-dcc9-4511-b7ea-185a4e28858a)

**Comment by scottchiefbaker** [comment]
Check the Apache logs, they will most likely have more information.

**Comment by longvo647912** [comment]
thank you

**Comment by longvo647912** [comment]
> Check the Apache logs, they will most likely have more information.

I think my version CentOS (7) not fit with new V-shell

<img width="1280" alt="image" src="https://github.com/NagiosEnterprises/nagiosvshell/assets/142724383/d7c9f2b3-116f-428a-b78f-2f5a0655e310">

Default values for these OS

<img width="653" alt="image" src="https://github.com/NagiosEnterprises/nagiosvshell/assets/142724383/6dd9b665-f5a4-4e62-91c9-c6aff5e8a8f3">

**Comment by longvo647912** [comment]
> Check the Apache logs, they will most likely have more information.

Can you help me editing value of  config.php file to fit with my OS (CentOS 7). I very need this for university graduation thesis
