### ISSUE TITLE
V-Shell and PNP4Nagios Discussion

### ISSUE THREAD

**Issue by EstebanMonge** [NagiosEnterprises/nagiosvshell#5]
Hello I want to insert in V Shell 2 pnp4nagios graphs.

I don't know about codeigniter, but I improvised a little and ugly patch.

Two files to /usr/local/vshell2/frontend/partials.

_host_pnp4nagios.html

``` html
    <section id="pnp4nagios" class="clearfix">
        <img src="/pnp4nagios/image?host={{ host.host_name }}&srv=_HOST_">
    </section>
```

and 
_service_pnp4nagios.html

``` html
<section id="pnp4nagios" class="clearfix">
        <img src="/pnp4nagios/image?host={{ service.host_name }}&srv={{ service.service_description }}">
</section>
```

I modified host-details.html:

``` html
<div ng-include="'frontend/partials/_host_pnp4nagios.html'" class="table-container partial-width full"></div>

    <div class="table-container partial-width full">

        <h3>Comments</h3>
```

And service-details.html

``` html
<div ng-include="'frontend/partials/_service_pnp4nagios.html'"></div>

    <div class="table-container partial-width full">

        <h3>Comments</h3>
```

And tadaaaaaa the graph appears!!! but I want to know how can I add a icon similar to Nagios CGI and a link in another place... I don't like the idea to charge the system if isn't necessary. This ugly patch is a client requeriments, they doesn't want to see Nagios CGIs... I don't want install Icinga 2... I love Nagios and now V Shell 2.

Also the graph isn't centered. I think that is better to V-Shell that detect if pnp4nagios is installed or configured in /etc/vshell2.conf

Or better that use action_url.

If this patch can be more standard can enhance the usability of v-shell.

Thanks

**Comment by hedenface** [comment]
Closing this since it's been ~3 years of activity. I'm not discounting the possibility - when we get back to vshell, we will definitely review the closed issues - but for now, lets get it off the open ticket/issues/bugs/whatever you call them. As always, re-open it if you think it's warranted.
